### ISSUE TITLE
Header with Section Navigation

### ISSUE THREAD

**Issue by alexrdrgz** [bizznest-dev/collaboration-repository-c#1]
#### Description
The task involves creating the website header based on the design provided in Figma. Additionally, implement navigation links that smoothly scroll the page to different sections upon clicking.

#### Tasks
- [x] Review the Figma design for the header component.
- [x] Create HTML/CSS structure for the header.
- [x] Implement navigation links to relevant sections of the site.
- [x] Test navigation functionality and smooth scrolling.
- [x] Ensure responsiveness and compatibility across devices.

<img width="932" alt="Screen Shot 2023-12-05 at 9 46 56 PM" src="https://github.com/bizznest-dev/collaboration-repository/assets/20450335/bc5c9bfa-618e-4a20-87f6-1e970c23893a">
